

# This file was *autogenerated* from the file ./DetFlowToDiGraph.sage
from sage.all_cmdline import *   # import sage library

_sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_2 = Integer(2)#!/usr/bin/env sage
# Created on Nov 27, 2020
# author: Hosein Hadipour
# contact: hsn.hadipour@gmail.com
import sys

def dtf_to_dg(file_name):
    with open(file_name, "r") as detfile:
        lns = detfile.readlines()
    output_buffer = ""
    known_variable_line_number = [i + _sage_const_1  for i in range(len(lns)) if "are initially known" in lns[i]]
    known_variables = lns[known_variable_line_number[_sage_const_0 ]].split(", ")
    known_variables[-_sage_const_1 ] = known_variables[-_sage_const_1 ].replace("\n", "")
    initial_guessed_vars_line_number = [i + _sage_const_1  for i in range(len(lns)) if "variable(s) are guessed:" in lns[i]]
    initial_guessed_vars = lns[initial_guessed_vars_line_number[_sage_const_0 ]].split(", ")
    initial_guessed_vars[-_sage_const_1 ] = initial_guessed_vars[-_sage_const_1 ].replace("\n", "")
    vertices = []
    edges = []
    cnt = _sage_const_0 
    for ln in lns:
        if "===>" in ln:
            temp = ln.split(": ")[_sage_const_1 ][:-_sage_const_1 ]
            temp = temp.split(" ===> ")
            rhs = temp[_sage_const_1 ]
            lhs_temp = temp[_sage_const_0 ].split(", ")
            lhs = []
            for el in lhs_temp:
                el = el.replace(" ", "")
                vertices.append(el)
                edges.append((el, rhs))
            cnt += _sage_const_1 
    # Symbolize vertices names
    vertices = list(map(var, vertices))
    initial_guessed_vars = list(map(var, initial_guessed_vars))
    vertices = list(set(vertices + initial_guessed_vars))
    # Symbolize edges' vertiices
    for i in range(len(edges)):
        edges[i] = (var(edges[i][_sage_const_0 ]), var(edges[i][_sage_const_1 ]))
    # Symbolize known_variables
    if known_variables != [""]:
        known_variables = list(map(var, known_variables))
    DG = DiGraph([vertices, edges])
    return vertices, edges, DG, known_variables

def main():
    if len(sys.argv) != _sage_const_2 :
        print("Usage: %s <n>" % sys.argv[_sage_const_0 ])
        sys.exit(_sage_const_1 )
    else:
        V, E, DG, known_variables = dtf_to_dg(file_name=sys.argv[_sage_const_1 ])
        LC = DG.connected_components_subgraphs()
        size_of_source = lambda x: len(x.sources())
        MSG = DiGraph()
        cnt = _sage_const_0 
        for sg in LC:
            print("Sub-graph %d: %s, Root size: %d, Number of vertices: %d" % (cnt, sg, len(sg.sources()), len(sg.vertices())))
            cnt += _sage_const_1 
            new_size = size_of_source(sg)
            current_size = size_of_source(MSG)
            if current_size < new_size:
                MSG = sg
        guessed_vars = MSG.sources()
        for kv in known_variables:
            if kv in guessed_vars:
                guessed_vars.remove(kv)
        print("Number of guessed variables: %d" % len(guessed_vars))
        print("Guessed variables: ")
        print(guessed_vars)
        #MSG.plot()
    
if __name__ == '__main__':
    main()

